spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: root
    username: postgres

  application:
    name: Spring_boot_jwt
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: postgresql
server:
  port: 9090

